### ISSUE TITLE
linear models

### ISSUE THREAD

**Issue by julieelarson** [caitlintwhite/KelmanProject#13] opened 2019-03-04 14:43 UTC
Hey Emily, 
I was just skimming your code and wanted to drop a couple notes about linear models --
First thing-- you can only plug in one response variable at a time (i.e. one trait at a time)... if you string a bunch of different traits together on the left side of the formula ( y + y + y ~ x), you'll notice you still only get one effect of SPEI estimated (my guess is it will just look at the first trait and ignore the others). So you'll need to run a separate model for each trait (just like you did with RMR CWV).

Second thing - When you're adding a best fit line to figures with geom_smooth, notice how the best fit line isn't really linear, but following the trend with the points?  I bet that type of trendline would be useful if you report some of those figures you created over time (year on x axis) because we don't necessarily expect a linear relationship over time, and we'd like to see the general bobs up and down (e.g., around drought years).  HOWEVER, looking at the trait X spei relationships, we do expect (and are looking for) a linear relationship. So we want that line that you fit through the data to show the best possible linear line through the data (not bobbing up and down). The way to do this would be to add an argument to the code: 

geom_smooth(method=lm)

^^^ kind of easy to remember, because it matches the actual statistical model code lm(y ~ x)

**Comment by emilykelman** [comment] 2019-03-04 18:52
Thanks, Julie
I added that linear trend line to the existing CWM trait X spei_12 figures, as well as ran linear regressions for all of the CWV trait/spei_12 relationships (both current and lagged). I also ran linear regressions for the CWM traits and current spei_12, but when I try to add lagged_spei12 to the tran_CWM_regressions DF so I can run the regression, I get the following error message (line 41):

Error in `$<-.data.frame`(`*tmp*`, lagged_spei12, value = c(NA, 0.0160587223013278,  : 
  replacement has 25 rows, data has 220

Also, when I graph the panel plot for transect level CWM and lagged spei_12 (line 152), a figure pops up but it comes with this warning message: 

Warning messages:
1: Removed 45 rows containing non-finite values (stat_smooth). 
2: Removed 45 rows containing missing values (geom_point). 

Is this just because there are some NA values in the tranCWM_figures DF?

**Comment by caitlintwhite** [comment] 2019-03-05 22:36
i think you two resolved this issue this morning so closing issue.

resolution was to use dplyr piping to create a lagged variable to a data frame through the 'mutate' function. when adding to transect-level data frame, you must use 'group_by' before mutate to split up the dataset by the transect, so that is created a t-1 lagged env variable for each transect.

**Closed as completed by caitlintwhite** 2019-03-05 22:36 UTC
